# Generated by Django 4.2.1 on 2023-06-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cart_ordermodel_city_ordermodel_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='streer',
            new_name='street',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
